In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [10]:
path='./dataCNN/'
label = pd.read_csv(path+'profile.txt', sep='\t', header=None)
label.columns = ['Cooler','Valve','Pump','Accumulator','Flag']
data = ['TS1.txt','TS2.txt','TS3.txt','TS4.txt']
df = pd.DataFrame()
for txt in data:
    read_df = pd.read_csv(path+txt, sep='\t', header=None)
    df = df.append(read_df)

In [11]:
df

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
0,35.570,35.492,35.469,35.422,35.414,35.320,35.227,35.242,35.160,35.176,...,36.008,35.984,35.996,36.039,36.008,36.008,36.094,36.102,36.090,36.152
1,36.156,36.094,35.992,36.008,35.992,35.902,35.824,35.820,35.727,35.727,...,37.328,37.324,37.340,37.332,37.316,37.410,37.418,37.422,37.488,37.477
2,37.488,37.391,37.340,37.312,37.223,37.145,37.059,36.973,36.898,36.879,...,38.457,38.461,38.457,38.469,38.469,38.555,38.527,38.543,38.527,38.621
3,38.633,38.535,38.469,38.379,38.297,38.223,38.125,38.062,37.977,37.969,...,39.441,39.363,39.367,39.457,39.461,39.461,39.473,39.441,39.453,39.461
4,39.461,39.461,39.375,39.281,39.203,39.113,39.043,38.969,38.875,38.883,...,40.324,40.320,40.312,40.340,40.320,40.387,40.391,40.391,40.387,40.391
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,30.383,30.375,30.379,30.363,30.367,30.391,30.383,30.363,30.375,30.402,...,30.383,30.395,30.406,30.383,30.406,30.422,30.402,30.395,30.402,30.379
2201,30.367,30.375,30.441,30.457,30.441,30.445,30.457,30.469,30.457,30.480,...,30.395,30.391,30.402,30.383,30.391,30.406,30.395,30.391,30.406,30.375
2202,30.375,30.375,30.367,30.375,30.367,30.375,30.379,30.367,30.367,30.391,...,30.480,30.484,30.480,30.488,30.480,30.480,30.484,30.395,30.480,30.379
2203,30.379,30.367,30.379,30.363,30.375,30.379,30.379,30.379,30.375,30.391,...,30.418,30.395,30.402,30.406,30.406,30.406,30.402,30.391,30.406,30.375
2204,30.355,30.379,30.379,30.375,30.367,30.375,30.367,30.363,30.367,30.383,...,30.395,30.402,30.395,30.402,30.391,30.395,30.391,30.395,30.402,30.375